### ISSUE TITLE
eslint-airbnb raises a warning

### ISSUE THREAD

**Issue by Oliphaunte** [Rulox/react-atomic-structure#24]
`npm WARN eslint-config-airbnb@11.1.0 requires a peer of eslint@^3.5.0 but none was installed.`
`npm WARN eslint-config-airbnb-base@7.1.0 requires a peer of eslint@^3.5.0 but none was installed.`

I'm not sure if this means it is not using the airbnb eslint or if we can ignore this. Should probably look into this at some point ¯\ _(ツ)_ /¯

**Comment by Rulox** [comment]
There's a solution; Use a custom config file based on the airbnb one @Oliphaunte

**Comment by Oliphaunte** [comment]
I think this issue can be closed now
