### ISSUE TITLE
Which test framework/tool should we use?

### ISSUE THREAD

**Issue by Rulox** [Rulox/react-atomic-structure#9]
Should we also do code coverage? I think we should.

There are some tools out there, Jest/Mocha/Instanbul/Jasmine, etc...

Discussion opened! @Oliphaunte

**Comment by Oliphaunte** [comment]
Yes, I only have experience with Mocah and Jasmine right now, I'll check out the others and see which looks best :3

**Comment by Rulox** [comment]
I saw Jest can be easy too

**Comment by Oliphaunte** [comment]
I agree, Jest seems to be the best option. I'll get on setting that up later today
